# Generated by Django 3.2.5 on 2021-07-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories_sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasEmailExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HasOptionalEmailExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
