# Generated by Django 3.2.5 on 2021-07-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories_sample', '0002_hasemailexample_hasoptionalemailexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasDescriptionExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HasRequiredDescriptionExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
