# Generated by Django 3.2.5 on 2021-07-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories_sample', '0003_hasdescriptionexample_hasrequireddescriptionexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasCoverPhotoExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HasRequiredCoverPhotoExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
