# Generated by Django 3.2.5 on 2021-07-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories_sample', '0004_hascoverphotoexample_hasrequiredcoverphotoexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasIconExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HasRequiredIconExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
