# Generated by Django 3.2.5 on 2021-08-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories_sample', '0005_hasiconexample_hasrequirediconexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasAvatarExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
