# Generated by Django 3.2.5 on 2021-07-22 23:01

import building_blocks.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_publishablehasuuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasInitialsExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
            ],
            bases=(building_blocks.mixins.HasInitials, models.Model),
        ),
    ]
