# Generated by Django 3.2.5 on 2021-07-29 21:19

import building_blocks.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_hasinitialsexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasAutoFieldsExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_upper', models.CharField(max_length=100)),
            ],
            bases=(building_blocks.models.mixins.HasAutoFields, models.Model),
        ),
    ]
