# Generated by Django 3.2.5 on 2021-07-30 17:05

from django.db import migrations, models
import sample.models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_timestampedexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUtilsExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(default=sample.models.default_json)),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
