# Generated by Django 3.2.5 on 2021-07-30 19:01

import building_blocks.models.fields
from django.db import migrations, models

import building_blocks.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_container_containeritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowerCaseCharFieldExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_field', building_blocks.models.fields.LowerCaseCharField(max_length=100)),
            ],
        ),
    ]
