# Generated by Django 3.2.5 on 2021-11-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_auto_20210831_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishablehasuuid',
            name='publishing_stage',
        ),
        migrations.RemoveField(
            model_name='publishablehasuuid',
            name='publishing_stage_changed_at',
        ),
        migrations.AddField(
            model_name='publishablehasuuid',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishablehasuuid',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
