# Generated by Django 3.2.5 on 2021-11-08 21:44

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_auto_20211105_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivablehasuuid',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='publishablehasuuid',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='publishablehasuuid',
            name='published_at',
        ),
        migrations.AddField(
            model_name='archivablehasuuid',
            name='status',
            field=django_fsm.FSMField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='publishablehasuuid',
            name='first_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishablehasuuid',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=50),
        ),
    ]
