# Generated by Django 3.2.5 on 2021-11-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_auto_20211105_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishablehasuuid',
            name='first_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
