# Generated by Django 3.2.5 on 2021-11-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_auto_20211108_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedStuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=99999)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'ordering': ('order', 'id'),
            },
        ),
    ]
