# Generated by Django 3.2.5 on 2022-01-25 02:54

import django_fsm
from django.db import migrations
from django.db.models import When, Value, Case

from building_blocks.models.enums import ArchiveStatus, PublishingStatus


def forwards_func_archivable(apps, schema_editor):
    ArchivableHasUUID = apps.get_model('sample', 'ArchivableHasUUID')
    db_alias = schema_editor.connection.alias
    ArchivableHasUUID.objects.using(db_alias).update(status1=Case(
        When(status='archived', then=Value(ArchiveStatus.archived)),
        default=Value(ArchiveStatus.active),
    ))


def reverse_func_archivable(apps, schema_editor):
    ArchivableHasUUID = apps.get_model('sample', 'ArchivableHasUUID')
    db_alias = schema_editor.connection.alias
    ArchivableHasUUID.objects.using(db_alias).update(status=Case(
        When(status1=ArchiveStatus.archived, then=Value('archived')),
        default=Value('active'),
    ))


def forwards_func_publishable(apps, schema_editor):
    PublishableHasUUID = apps.get_model('sample', 'PublishableHasUUID')
    db_alias = schema_editor.connection.alias
    PublishableHasUUID.objects.using(db_alias).update(status1=Case(
        When(status='published', then=Value(PublishingStatus.published)),
        When(status='archived', then=Value(PublishingStatus.archived)),
        default=Value(PublishingStatus.draft),
    ))


def reverse_func_publishable(apps, schema_editor):
    PublishableHasUUID = apps.get_model('sample', 'PublishableHasUUID')
    db_alias = schema_editor.connection.alias
    PublishableHasUUID.objects.using(db_alias).update(status=Case(
        When(status1=PublishingStatus.published, then=Value('published')),
        When(status1=PublishingStatus.archived, then=Value('archived')),
        default=Value('draft'),
    ))


class Migration(migrations.Migration):
    dependencies = [
        ('sample', '0013_orderedstuff'),
    ]

    operations = [
        # For Archivable model
        migrations.AddField(
            model_name='archivablehasuuid',
            name='status1',
            field=django_fsm.FSMIntegerField(choices=[(100, 'Active'), (-1, 'Archived')], default=100),
        ),
        migrations.RunPython(forwards_func_archivable, reverse_func_archivable),
        migrations.RemoveField(
            model_name='archivablehasuuid',
            name='status',
        ),
        migrations.RenameField(
            model_name='archivablehasuuid',
            old_name='status1',
            new_name='status',
        ),
        # For Publishable model
        migrations.AddField(
            model_name='publishablehasuuid',
            name='status1',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Draft'), (100, 'Published'), (-1, 'Archived')], default=0),
        ),
        migrations.RunPython(forwards_func_publishable, reverse_func_publishable),
        migrations.RemoveField(
            model_name='publishablehasuuid',
            name='status',
        ),
        migrations.RenameField(
            model_name='publishablehasuuid',
            old_name='status1',
            new_name='status',
        ),
    ]
