# Generated by Django 3.2.5 on 2022-01-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0014_int_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivablehasuuid',
            old_name='status',
            new_name='_status',
        ),
        migrations.RenameField(
            model_name='publishablehasuuid',
            old_name='status',
            new_name='_status',
        ),
    ]
