# Generated by Django 3.2.5 on 2021-07-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex_factories_sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasAutoCodeGenerateFunctionExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
