# Generated by Django 3.2.5 on 2021-07-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex_factories_sample', '0002_hasautocodegeneratefunctionexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasAutoSlugExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
