# Generated by Django 3.2.5 on 2021-07-27 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complex_factories_sample', '0003_hasautoslugexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasUserLimitedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('see_all_hasuserlimitedaccess', 'Can see all HasUserLimitedAccess')],
            },
        ),
    ]
