name: django-building-blocks
version: 0.2.0-dev2
description: Abstract Django base models to act as building blocks for rapid development of Django database models

repo_url: https://github.com/kaoslabsinc/django-building-blocks
project_url: https://github.com/kaoslabsinc/django-building-blocks
keywords: django, abstract, models, building blocks, database models
