# Generated by Django 4.1.1 on 2022-10-18 22:10

import building_blocks.models.interfaces
import dj_kaos_utils.models.fields
import dj_kaos_utils.models.mixins
from django.db import migrations, models
import django.utils.timezone
import django_fsm
import model_utils.fields
import rules.contrib.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_productstatusarchivable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPublishable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'Draft'), (100, 'Published'), (-1, 'Archived')], default=0)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('price', dj_kaos_utils.models.fields.MoneyField()),
            ],
            options={
                'abstract': False,
            },
            bases=(building_blocks.models.interfaces.ArchivableInterface, dj_kaos_utils.models.mixins.HasAutoFields, rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
